In [1]:
import pandas as pd

In [2]:
df = pd.read_pickle('second_dataframe.pickle')
df

,,,sviatok,poznámka
datum,meniny,moz,,
2023-01-01,Nový rok,0,PRIKÁZANÁ SLÁVNOSŤ:\nPanny Márie Bohorodičky [...,Vianočné obdobie; lit. rok: 2023; ned./fer. cy...
2023-01-02,"Alexandra, Karina",0,"Svätých Bazila Veľkého a Gregora Nazianzského,...",Vianočné obdobie; lit. rok: 2023; ned./fer. cy...
2023-01-03,Daniela,0,Utorok vo Vianočnom období [Biela]\nalebo\nNaj...,Vianočné obdobie; lit. rok: 2023; ned./fer. cy...
2023-01-04,Drahoslav,0,Streda vo Vianočnom období [Biela],Vianočné obdobie; lit. rok: 2023; ned./fer. cy...
2023-01-05,Andrea,0,Štvrtok vo Vianočnom období [Biela],Vianočné obdobie; lit. rok: 2023; ned./fer. cy...
...,...,...,...,...
2023-12-27,Filoména,0,"Svätého Jána, apoštola a evanjelistu [Biela]\n...",Vianočné obdobie; lit. rok: 2024; ned./fer. cy...
2023-12-28,"Ivana, Ivona",0,"Svätých Neviniatok, mučeníkov [Červená]\n(svia...",Vianočné obdobie; lit. rok: 2024; ned./fer. cy...
2023-12-29,Milada,0,Piaty deň v oktáve narodenia Pána [Biela],Vianočné obdobie; lit. rok: 2024; ned./fer. cy...
2023-12-30,Dávid,0,Šiesty deň v oktáve narodenia Pána [Biela],Vianočné obdobie; lit. rok: 2024; ned./fer. cy...
2023-12-31,Silvester,0,"Svätej rodiny – Ježiša, Márie a Jozefa [Biela]...",Vianočné obdobie; lit. rok: 2024; ned./fer. cy...

In [3]:
# vytvoríme si samostatný frame, pozostávajúci z df.index
# ten si postupne upravíme (pridáme stĺpce / zmažeme) do požadovanej formy.
# nakoniec vytvoríme z framu Multiindex, a napojíme ho do pôvodného df.index

In [4]:
# vytvoríme si samostatný frame, pozostávajúci z df.index
frame_index = df.index.to_frame().reset_index(drop=True)
frame_index

          datum             meniny moz
0    2023-01-01           Nový rok   0
1    2023-01-02  Alexandra, Karina   0
2    2023-01-03            Daniela   0
3    2023-01-04          Drahoslav   0
4    2023-01-05             Andrea   0
..          ...                ...  ..
391  2023-12-27           Filoména   0
392  2023-12-28       Ivana, Ivona   0
393  2023-12-29             Milada   0
394  2023-12-30              Dávid   0
395  2023-12-31          Silvester   0

[396 rows x 3 columns]

In [5]:
# konverzia datum string na datetime
frame_index['datum'] = pd.to_datetime(frame_index['datum']) 
frame_index.head()

       datum             meniny moz
0 2023-01-01           Nový rok   0
1 2023-01-02  Alexandra, Karina   0
2 2023-01-03            Daniela   0
3 2023-01-04          Drahoslav   0
4 2023-01-05             Andrea   0

In [6]:
# generujeme nový stĺpec: deň v mesiaci
d_mes = frame_index['datum'].dt.day.astype(str) + '. ' + frame_index['datum'].dt.month_name('sk_SK').str.lower()
frame_index.insert(1, 'd_mes', d_mes)
frame_index.head()

       datum      d_mes             meniny moz
0 2023-01-01  1. január           Nový rok   0
1 2023-01-02  2. január  Alexandra, Karina   0
2 2023-01-03  3. január            Daniela   0
3 2023-01-04  4. január          Drahoslav   0
4 2023-01-05  5. január             Andrea   0

In [7]:
# generujeme nový stĺpec: deň v týždni
d_tyz = frame_index['datum'].dt.day_name('sk_SK').str.lower()
frame_index.insert(2, 'd_tyz', d_tyz)
frame_index.head()

       datum      d_mes     d_tyz             meniny moz
0 2023-01-01  1. január    nedeľa           Nový rok   0
1 2023-01-02  2. január  pondelok  Alexandra, Karina   0
2 2023-01-03  3. január    utorok            Daniela   0
3 2023-01-04  4. január    streda          Drahoslav   0
4 2023-01-05  5. január   štvrtok             Andrea   0

In [8]:
# datum back to string
frame_index['datum'] = frame_index.loc[:,'datum'].astype(str)
frame_index.head()

        datum      d_mes     d_tyz             meniny moz
0  2023-01-01  1. január    nedeľa           Nový rok   0
1  2023-01-02  2. január  pondelok  Alexandra, Karina   0
2  2023-01-03  3. január    utorok            Daniela   0
3  2023-01-04  4. január    streda          Drahoslav   0
4  2023-01-05  5. január   štvrtok             Andrea   0

In [9]:
# generujeme stĺpec deň - ako bude vyzerať vo výslednej html tabuľke.
den = frame_index.d_mes + ', ' + frame_index.d_tyz + '<br><i>' + frame_index.meniny +'</i>'
frame_index.insert(1, 'den', den)
frame_index.head()

,datum,den,d_mes,d_tyz,meniny,moz
0,2023-01-01,"1. január, nedeľa<br><i>Nový rok</i>",1. január,nedeľa,Nový rok,0
1,2023-01-02,"2. január, pondelok<br><i>Alexandra, Karina</i>",2. január,pondelok,"Alexandra, Karina",0
2,2023-01-03,"3. január, utorok<br><i>Daniela</i>",3. január,utorok,Daniela,0
3,2023-01-04,"4. január, streda<br><i>Drahoslav</i>",4. január,streda,Drahoslav,0
4,2023-01-05,"5. január, štvrtok<br><i>Andrea</i>",5. január,štvrtok,Andrea,0

In [10]:
# mažeme prebytočné stĺpce
frame_index.drop(['d_tyz','d_mes','meniny'], axis='columns', inplace=True)
frame_index.head()

        datum                                              den moz
0  2023-01-01             1. január, nedeľa<br><i>Nový rok</i>   0
1  2023-01-02  2. január, pondelok<br><i>Alexandra, Karina</i>   0
2  2023-01-03              3. január, utorok<br><i>Daniela</i>   0
3  2023-01-04            4. január, streda<br><i>Drahoslav</i>   0
4  2023-01-05              5. január, štvrtok<br><i>Andrea</i>   0

In [11]:
# vytvárame MultiIndex
new_multiindex = pd.MultiIndex.from_frame(frame_index)
new_multiindex[:5]

MultiIndex([('2023-01-01', ...),
            ('2023-01-02', ...),
            ('2023-01-03', ...),
            ('2023-01-04', ...),
            ('2023-01-05', ...)],
           names=['datum', 'den', 'moz'])

In [12]:
# prepisujeme df.index novým multiindexom
df.index = new_multiindex # alebo: df = df.set_index(new_multiindex)
df

,,,sviatok,poznámka
datum,den,moz,,
2023-01-01,"1. január, nedeľa<br><i>Nový rok</i>",0,PRIKÁZANÁ SLÁVNOSŤ:\nPanny Márie Bohorodičky [...,Vianočné obdobie; lit. rok: 2023; ned./fer. cy...
2023-01-02,"2. január, pondelok<br><i>Alexandra, Karina</i>",0,"Svätých Bazila Veľkého a Gregora Nazianzského,...",Vianočné obdobie; lit. rok: 2023; ned./fer. cy...
2023-01-03,"3. január, utorok<br><i>Daniela</i>",0,Utorok vo Vianočnom období [Biela]\nalebo\nNaj...,Vianočné obdobie; lit. rok: 2023; ned./fer. cy...
2023-01-04,"4. január, streda<br><i>Drahoslav</i>",0,Streda vo Vianočnom období [Biela],Vianočné obdobie; lit. rok: 2023; ned./fer. cy...
2023-01-05,"5. január, štvrtok<br><i>Andrea</i>",0,Štvrtok vo Vianočnom období [Biela],Vianočné obdobie; lit. rok: 2023; ned./fer. cy...
...,...,...,...,...
2023-12-27,"27. december, streda<br><i>Filoména</i>",0,"Svätého Jána, apoštola a evanjelistu [Biela]\n...",Vianočné obdobie; lit. rok: 2024; ned./fer. cy...
2023-12-28,"28. december, štvrtok<br><i>Ivana, Ivona</i>",0,"Svätých Neviniatok, mučeníkov [Červená]\n(svia...",Vianočné obdobie; lit. rok: 2024; ned./fer. cy...
2023-12-29,"29. december, piatok<br><i>Milada</i>",0,Piaty deň v oktáve narodenia Pána [Biela],Vianočné obdobie; lit. rok: 2024; ned./fer. cy...
2023-12-30,"30. december, sobota<br><i>Dávid</i>",0,Šiesty deň v oktáve narodenia Pána [Biela],Vianočné obdobie; lit. rok: 2024; ned./fer. cy...
2023-12-31,"31. december, nedeľa<br><i>Silvester</i>",0,"Svätej rodiny – Ježiša, Márie a Jozefa [Biela]...",Vianočné obdobie; lit. rok: 2024; ned./fer. cy...

In [13]:
# dopĺňam diakritiku do názvov
df.index.names = ['dátum', 'deň', 'moz']
df.head()

,,,sviatok,poznámka
dátum,deň,moz,,
2023-01-01,"1. január, nedeľa<br><i>Nový rok</i>",0,PRIKÁZANÁ SLÁVNOSŤ:\nPanny Márie Bohorodičky [...,Vianočné obdobie; lit. rok: 2023; ned./fer. cy...
2023-01-02,"2. január, pondelok<br><i>Alexandra, Karina</i>",0,"Svätých Bazila Veľkého a Gregora Nazianzského,...",Vianočné obdobie; lit. rok: 2023; ned./fer. cy...
2023-01-03,"3. január, utorok<br><i>Daniela</i>",0,Utorok vo Vianočnom období [Biela]\nalebo\nNaj...,Vianočné obdobie; lit. rok: 2023; ned./fer. cy...
2023-01-04,"4. január, streda<br><i>Drahoslav</i>",0,Streda vo Vianočnom období [Biela],Vianočné obdobie; lit. rok: 2023; ned./fer. cy...
2023-01-05,"5. január, štvrtok<br><i>Andrea</i>",0,Štvrtok vo Vianočnom období [Biela],Vianočné obdobie; lit. rok: 2023; ned./fer. cy...

In [14]:
# skrývame nepotrebné levely v indexe,
# a ukladáme do stringu
s = df.style.hide(level=['dátum','moz']).to_html()

In [15]:
# css štýly tabuľky
css = """
<style>
  table {
    width: 75%;
    margin-left: auto;
    margin-right: auto;
    font-family: Arial, Helvetica, sans-serif;
    line-height: 1.5;
  }

  table,
  th,
  td {
    border: 1px solid black;
    border-collapse: collapse;
    padding: 1rem;
  }

  td {
    white-space: pre-wrap;
  }

  th {
    text-wrap: nowrap;
    font-weight: normal;
  }

  .col_heading,
  .index_name {
    font-weight: bold;
  }

  .col1 {
    /* font-size: smaller; */
  }
 
</style>
"""

In [16]:
# tvorba výsledného html súboru.
with open('resulting_table.html', mode='w', encoding='utf8') as f:
    f.write(css)
    f.write(s)

In [55]:
# done